import {
  isSocialConfigured, signInWithGoogle, getCurrentUser, signOut, onAuthChange,
  loadLearningState, saveLearningState, saveDiagnosticResults
} from "./social.js";
import { curriculum, diagnosticQuestions, allQuestions } from "./learning.js";
import { NUCLEO_CONFIG } from "./config.js";

const subjects = {
  quimica: { name:"Química", cls:"chem", icon:"⬡", color:"#d86b48", method:"Representaciones múltiples + recuperación activa", description:"Conecta lo macroscópico, lo molecular y lo simbólico; luego recupera relaciones, mecanismos y cálculos sin apoyo.", steps:["Predice antes de calcular","Traduce entre partículas, símbolos y evidencia","Resuelve sin mirar el ejemplo","Explica el error y vuelve a intentarlo"] },
  fisica: { name:"Física", cls:"physics", icon:"↗", color:"#4d69cc", method:"Ejemplos resueltos + práctica intercalada", description:"Construye el modelo antes de sustituir números y alterna tipos de problema para aprender a elegir principios.", steps:["Dibuja el sistema y declara supuestos","Selecciona el principio físico","Resuelve simbólicamente","Comprueba unidades y orden de magnitud"] },
  biologia: { name:"Biología", cls:"bio", icon:"⌘", color:"#3b8e68", method:"Recuperación activa + elaboración causal", description:"Reconstruye procesos de memoria, compara sistemas y explica cómo una estructura habilita una función.", steps:["Reconstruye el proceso sin apuntes","Dibuja relaciones y flujos","Explica cada flecha causalmente","Contrasta casos y corrige vacíos"] },
  calculo: { name:"Cálculo", cls:"calculus", icon:"∫", color:"#8a5bc2", method:"Ejemplos trabajados + práctica variada", description:"Conecta definición, representación gráfica y procedimiento; después decide qué herramienta aplicar en problemas nuevos.", steps:["Interpreta gráfica y definición","Estudia un ejemplo trabajado","Resuelve una variación sin apoyo","Verifica y explica cada decisión"] }
};

const initial = { reviews:0, streak:0, lastStudyDate:null, completed:[], focusMinutes:0, xp:0, coins:0, questClaims:[], battleWins:0, mastery:{}, events:[], plans:{}, communityPosts:[], curriculumPreferences:{} };
let state = loadLocal();
let currentUser = null;
let cloudTimer = null;
let timer = { remaining:25*60, id:null };
let roomTimer = { remaining:25*60, id:null };
const app = document.querySelector("#app");

function loadLocal(){ try{return {...structuredClone(initial),...JSON.parse(localStorage.getItem("nucleo-state"))}}catch{return structuredClone(initial)} }
function save(){
  localStorage.setItem("nucleo-state",JSON.stringify(state));
  if(currentUser&&isSocialConfigured()){
    clearTimeout(cloudTimer);
    cloudTimer=setTimeout(()=>saveLearningState(state).catch(()=>toast("Guardado local; la nube no respondió")),450);
  }
  updateChrome();
}
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function escapeHTML(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function fmtDate(value,options={}){return new Intl.DateTimeFormat("es-GT",{day:"numeric",month:"short",...options}).format(new Date(value))}
function relative(value){const days=Math.ceil((new Date(value)-new Date())/864e5);if(days<0)return`Hace ${Math.abs(days)} día${Math.abs(days)===1?"":"s"}`;return days===0?"Hoy":days===1?"Mañana":`En ${days} días`}
function displayName(){return currentUser?.user_metadata?.full_name||currentUser?.user_metadata?.name||"Estudiante"}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"NU"}
function subjectMastery(key){const values=Object.values(state.mastery?.[key]||{}).filter(Number.isFinite);return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null}
function overallMastery(){const values=Object.keys(curriculum).map(subjectMastery).filter(Number.isFinite);return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):null}
function masteryLabel(value){return Number.isFinite(value)?`${value}%`:"Sin diagnóstico"}
function levelInfo(){const level=Math.floor(Math.sqrt((state.xp||0)/100))+1,floor=(level-1)**2*100,ceiling=level**2*100,names=["Aprendiz","Explorador","Analista","Investigador","Maestro","Erudito"];return{level,name:names[Math.min(level-1,names.length-1)],progress:Math.round(((state.xp-floor)/(ceiling-floor))*100),next:ceiling-state.xp}}
function registerStudyDay(){const today=new Date().toISOString().slice(0,10);if(state.lastStudyDate===today)return;const yesterday=new Date(Date.now()-864e5).toISOString().slice(0,10);state.streak=state.lastStudyDate===yesterday?(state.streak||0)+1:1;state.lastStudyDate=today}
function awardXP(amount,reason){const before=levelInfo().level;state.xp+=amount;state.coins+=Math.ceil(amount/5);registerStudyDay();save();const after=levelInfo().level;toast(after>before?`¡Nivel ${after} desbloqueado!`:`+${amount} XP · ${reason}`)}
function supportedEvent(event){return Boolean(subjects[event.course])}
function sortedEvents(){return[...(state.events||[])].sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt))}
function shuffle(items){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}

const pages={inicio:renderHome,agenda:renderAgenda,plan:renderPlan,diagnostico:renderDiagnostics,misiones:renderQuests,grupo:renderGroup,arena:renderArena,metodo:renderMethod,quimica:()=>renderSubject("quimica"),fisica:()=>renderSubject("fisica"),biologia:()=>renderSubject("biologia"),calculo:()=>renderSubject("calculo")};
function route(){
  const key=location.hash.slice(1)||"inicio";
  const labels={inicio:["ESPACIO PERSONAL","Inicio"],agenda:["PLANIFICACIÓN","Mi agenda"],plan:["ADAPTATIVO","Plan personal"],diagnostico:["EVALUACIÓN","Diagnóstico"],misiones:["AVENTURA","Misiones"],grupo:["COLABORACIÓN","Grupo de estudio"],arena:["DESAFÍOS","Arena científica"],metodo:["SISTEMA","Mi método"],quimica:["ASIGNATURA","Química"],fisica:["ASIGNATURA","Física"],biologia:["ASIGNATURA","Biología"],calculo:["ASIGNATURA","Cálculo"]};
  document.querySelectorAll(".nav-item[data-route]").forEach(x=>x.classList.toggle("active",x.dataset.route===key));
  document.querySelector("#section-kicker").textContent=(labels[key]||labels.inicio)[0];document.querySelector("#section-title").textContent=(labels[key]||labels.inicio)[1];
  (pages[key]||renderHome)();document.querySelector("#sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"});
}
function eventCard(event,compact=false){
  const s=subjects[event.course],icon=s?.icon||"□",cls=s?.cls||"other",course=s?.name||event.courseName||"Otro curso",topic=s&&event.topic?curriculum[event.course].topics[event.topic]?.name:"";
  const action=s?`<button class="go" data-study="${event.course}">Estudiar →</button>`:`<button class="go" data-complete="${event.id}">Completar</button>`;
  return`<div class="task event-${event.type} ${compact?"compact":""}"><span class="task-icon ${cls}">${event.type==="exam"?"!":icon}</span><div><strong>${escapeHTML(event.title)}</strong><small>${escapeHTML(course)}${topic?` · ${escapeHTML(topic)}`:""} · ${relative(event.dueAt)}, ${fmtDate(event.dueAt,{hour:"numeric",minute:"2-digit"})}</small></div>${action}</div>`;
}
function renderHome(){
  const pending=sortedEvents().filter(e=>!state.completed.includes(e.id)),today=new Date(),firstName=displayName().split(" ")[0];
  app.innerHTML=`<section class="hero"><div><p class="eyebrow">HOLA, ${escapeHTML(firstName).toUpperCase()}</p><h1>Hoy construimos<br><em>memoria duradera.</em></h1><p>La ruta prioriza fechas próximas y conceptos con menor dominio. Las actividades las decides tú; el sistema organiza cómo prepararlas.</p></div><div class="date-chip">${new Intl.DateTimeFormat("es-GT",{weekday:"long",day:"numeric",month:"long"}).format(today)}</div></section>
  <section class="rpg-banner"><div><p class="eyebrow" style="color:var(--lime)">RUTA DEL CONOCIMIENTO · ${levelInfo().name.toUpperCase()}</p><h2>${state.xp} XP acumulados</h2><p>Faltan ${levelInfo().next} XP para el siguiente nivel. La experiencia se obtiene recuperando, aplicando y concentrándote.</p></div><div class="level-large">${levelInfo().level}</div></section>
  <div class="metrics"><div class="card metric"><small>DOMINIO MEDIDO</small><strong>${masteryLabel(overallMastery())}</strong><span><a href="#diagnostico">Actualizar diagnóstico →</a></span></div><div class="card metric"><small>PRÓXIMOS EXÁMENES</small><strong>${pending.filter(e=>e.type==="exam").length}</strong><span><a href="#plan">Ver preparación →</a></span></div><div class="card metric"><small>RACHA ACTUAL</small><strong>${state.streak||0} días</strong><span>Constancia real</span></div></div>
  <div class="dashboard-grid"><div><article class="card today-card"><div class="today-head"><div><small>PRIORIDAD ACTUAL</small><strong>${Math.min(3,pending.length)} acciones próximas</strong></div><button class="mini-add" data-new-event>＋</button></div><div class="task-list">${pending.length?pending.slice(0,3).map(e=>eventCard(e,true)).join(""):'<div class="empty">Tu agenda está vacía. Añade una actividad para construir tu ruta.</div>'}</div></article><article class="card" style="margin-top:20px"><div class="card-title"><h2>Preparación automática</h2><a href="#plan">Abrir plan →</a></div>${nextPlanPreview()}</article></div>
  <div><article class="card"><div class="card-title"><h2>Repaso por asignatura</h2><button class="text-button" data-study="mixed">Intercalar</button></div><div class="review-list">${Object.entries(subjects).map(([key,s])=>`<div class="review-item"><span class="badge ${s.cls}">${s.icon}</span><div><strong>${s.name}</strong><small>${masteryLabel(subjectMastery(key))}</small></div><button data-study="${key}">→</button></div>`).join("")}</div></article><article class="card insight" style="margin-top:20px"><p class="eyebrow">IDEA DEL DÍA</p><blockquote>“Reconocer una respuesta no equivale a poder producirla. Cierra los apuntes y recupérala.”</blockquote></article></div></div>`;
  bindCommon();
}
function nextPlanPreview(){const exam=sortedEvents().find(e=>e.type==="exam"&&supportedEvent(e)&&!state.completed.includes(e.id));if(!exam)return'<div class="empty">Añade un examen de Química, Física, Biología o Cálculo para generar un plan.</div>';const plan=state.plans[exam.id]||generateExamPlan(exam),next=plan.sessions.find(x=>new Date(`${x.date}T23:59`)>=new Date())||plan.sessions.at(-1);return`<div class="plan-preview"><span class="exam-chip">EXAMEN · ${relative(exam.dueAt)}</span><h3>${escapeHTML(exam.title)}</h3><p><strong>Siguiente:</strong> ${escapeHTML(next?.title||"Simulacro final")} · ${next?.minutes||30} min</p></div>`}
function renderSubject(key){
  const s=subjects[key],events=sortedEvents().filter(e=>e.course===key&&!state.completed.includes(e.id));
  app.innerHTML=`<section class="subject-hero ${s.cls}"><p class="eyebrow">${s.method.toUpperCase()}</p><h1>${s.name}</h1><p>${s.description}</p><div class="subject-stats"><div><strong>${masteryLabel(subjectMastery(key))}</strong><small>Dominio medido</small></div><div><strong>${Object.keys(curriculum[key].topics).length}</strong><small>Macrotemas</small></div><div><strong>${events.length}</strong><small>Actividades</small></div></div></section><div class="tabs"><button class="tab active">Ruta de estudio</button><button class="tab" data-study="${key}">Repaso activo</button><button class="tab" data-new-event>Nueva actividad</button></div>
  <div class="method-grid"><article class="card method-card"><p class="eyebrow">SECUENCIA RECOMENDADA</p><h3>${s.method}</h3><p>Cada sesión exige producir una respuesta antes de consultar la solución.</p>${s.steps.map((x,i)=>`<div class="method-step"><span class="step-num">0${i+1}</span><div><h3>${x}</h3><p>${i===0?"Activa conocimientos previos y define el problema.":i===3?"Registra la dificultad para espaciar el siguiente intento.":"Haz visible el razonamiento, no solo el resultado."}</p></div></div>`).join("")}<button class="primary full" data-study="${key}">Comenzar recuperación</button></article>
  <div><article class="card"><div class="card-title"><h2>Macrotemas base</h2><a href="#diagnostico">Evaluar →</a></div>${Object.entries(curriculum[key].topics).map(([id,t])=>`<div class="assignment-row"><i class="indicator" style="background:${s.color}"></i><div><strong>${escapeHTML(t.name)}</strong><small>${masteryLabel(state.mastery?.[key]?.[id]??null)}</small></div><button class="go" data-diagnostic="${key}:${id}">Diagnóstico</button></div>`).join("")}</article><article class="card" style="margin-top:18px"><div class="card-title"><h2>Agenda de ${s.name}</h2><button class="text-button" data-new-event>Agregar</button></div>${events.length?events.map(e=>eventCard(e,true)).join(""):'<div class="empty">No hay actividades pendientes para este curso.</div>'}</article></div></div>`;
  bindCommon();bindDiagnosticButtons();
}
function renderAgenda(){
  const events=sortedEvents(),groups=events.reduce((acc,e)=>((acc[new Date(e.dueAt).toISOString().slice(0,10)]||=[]).push(e),acc),{});
  app.innerHTML=`<section class="hero"><div><p class="eyebrow">CONTROL PERSONAL</p><h1>Agenda académica</h1><p>Registra tareas, proyectos y exámenes. Los exámenes aparecen en rojo y, si pertenecen a un curso compatible, activan una preparación automática.</p></div><button class="primary" data-new-event>＋ Nueva actividad</button></section><div class="legend"><span><i class="legend-task"></i>Tarea</span><span><i class="legend-project"></i>Proyecto</span><span><i class="legend-exam"></i>Examen</span></div>
  <div class="agenda-layout"><div>${Object.keys(groups).length?Object.entries(groups).map(([date,items])=>`<section class="agenda-day"><h3>${new Intl.DateTimeFormat("es-GT",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${date}T12:00`))}</h3><article class="card agenda-events">${items.map(e=>`${eventCard(e)}<div class="event-actions"><button class="text-button" data-complete="${e.id}">${state.completed.includes(e.id)?"Reabrir":"Marcar completada"}</button><button class="text-button danger" data-delete="${e.id}">Eliminar</button></div>`).join("")}</article></section>`).join(""):'<article class="card empty">No tienes actividades todavía.</article>'}</div><aside><article class="card focus-card"><p class="eyebrow" style="color:var(--lime)">BLOQUE DE ENFOQUE</p><div class="timer" id="timer-display">25:00</div><p>Una tarea, sin notificaciones. Al terminar registra el progreso.</p><button class="primary full" id="timer-toggle">Iniciar enfoque</button><button class="secondary full" id="timer-reset">Reiniciar</button></article></aside></div>`;
  bindCommon();bindTimer();
}
function generateExamPlan(event){
  if(!supportedEvent(event))return null;
  const examDate=new Date(event.dueAt),days=Math.max(1,Math.ceil((examDate-new Date())/864e5)),available=Math.min(days,10),topicName=curriculum[event.course].topics[event.topic]?.name||"todos los macrotemas";
  const templates=[["Diagnóstico de recuperación",`Responde sin apuntes sobre ${topicName}; registra lagunas, no solo errores.`,25],["Comprensión y ejemplo trabajado",`Reconstruye ideas clave de ${topicName} y explica cada paso o relación causal.`,40],["Práctica guiada","Resuelve variaciones con retroalimentación inmediata y crea un registro de errores.",45],["Recuperación espaciada","Contesta preguntas y reproduce procedimientos desde memoria.",30],["Práctica intercalada","Mezcla el tema del examen con conceptos cercanos para elegir el método correcto.",45],["Simulacro sin apoyo","Resuelve un bloque cronometrado y corrige explicando la causa de cada error.",60],["Repaso final ligero","Recupera fórmulas, mecanismos y errores frecuentes; evita aprendizaje nuevo.",25]];
  const count=Math.max(3,Math.min(templates.length,available)),selected=count===templates.length?templates:Array.from({length:count},(_,i)=>templates[Math.round(i*(templates.length-1)/(count-1))]);
  const sessions=selected.map((item,i)=>{const offset=Math.max(1,Math.round((days-1)*(selected.length-1-i)/Math.max(1,selected.length-1))),date=new Date(examDate);date.setDate(date.getDate()-offset);return{id:uid(),date:date.toISOString().slice(0,10),title:item[0],detail:item[1],minutes:Math.min(item[2],Math.max(20,Math.round((event.hours||2)*60/count)))}});
  const plan={eventId:event.id,generatedAt:new Date().toISOString(),sessions};state.plans[event.id]=plan;return plan;
}
function renderPlan(){
  const exams=sortedEvents().filter(e=>e.type==="exam"&&!state.completed.includes(e.id)),weak=Object.entries(subjects).map(([key,s])=>({key,name:s.name,score:subjectMastery(key)})).sort((a,b)=>(a.score??-1)-(b.score??-1));
  app.innerHTML=`<section class="hero"><div><p class="eyebrow">RUTA ADAPTATIVA</p><h1>Programa personal</h1><p>Combina fechas reales, dominio diagnosticado y práctica espaciada. Cambia cuando agregas un examen o actualizas un diagnóstico.</p></div><button class="primary" data-new-event>Agregar examen</button></section><div class="metrics"><div class="card metric"><small>PRIORIDAD CONCEPTUAL</small><strong>${weak[0].score===null?"Diagnosticar":weak[0].name}</strong><span>${masteryLabel(weak[0].score)}</span></div><div class="card metric"><small>SESIONES PROGRAMADAS</small><strong>${exams.reduce((n,e)=>n+(state.plans[e.id]?.sessions.length||generateExamPlan(e)?.sessions.length||0),0)}</strong><span>Hasta tus exámenes</span></div><div class="card metric"><small>CARGA ESTIMADA</small><strong>${exams.reduce((n,e)=>n+Number(e.hours||0),0)} h</strong><span>Declarada por ti</span></div></div>${exams.length?exams.map(examPlanHTML).join(""):'<article class="card empty">Añade un examen para crear una preparación. Mientras tanto, realiza un diagnóstico.</article>'}`;
  bindCommon();
}
function examPlanHTML(exam){
  const s=subjects[exam.course];if(!s)return`<article class="card plan-card unsupported"><span class="exam-chip">EXAMEN EXTERNO</span><h2>${escapeHTML(exam.title)}</h2><p>Queda en la agenda, pero Núcleo no genera contenido para ${escapeHTML(exam.courseName||"este curso")} porque todavía no posee su temario.</p></article>`;
  const plan=state.plans[exam.id]||generateExamPlan(exam);return`<article class="card plan-card"><div class="plan-head"><div><span class="exam-chip">${s.icon} ${s.name.toUpperCase()} · ${relative(exam.dueAt)}</span><h2>${escapeHTML(exam.title)}</h2><p>${escapeHTML(curriculum[exam.course].topics[exam.topic]?.name||"Evaluación general")} · ${fmtDate(exam.dueAt,{year:"numeric",hour:"numeric",minute:"2-digit"})}</p></div><button class="secondary" data-regenerate="${exam.id}">Recalcular</button></div><div class="timeline">${plan.sessions.map((x,i)=>`<div class="plan-session"><span>${i+1}</span><div><small>${fmtDate(`${x.date}T12:00`,{weekday:"short"})} · ${x.minutes} min</small><strong>${escapeHTML(x.title)}</strong><p>${escapeHTML(x.detail)}</p></div><button class="go" data-study="${exam.course}">Practicar</button></div>`).join("")}</div></article>`;
}
function renderDiagnostics(){app.innerHTML=`<section class="hero"><div><p class="eyebrow">LÍNEA BASE REAL</p><h1>Diagnóstico de dominio</h1><p>Evalúa un macrotema concreto o todo un curso. Solo se muestra un porcentaje después de responder.</p></div></section><div class="confidence-note">Estas pruebas breves orientan la práctica; no equivalen a una calificación certificada.</div>${Object.entries(curriculum).map(([key,s])=>`<section class="diagnostic-subject"><div class="card-title" style="margin-top:25px"><h2>${s.icon} ${s.name}</h2><button class="primary" data-diagnostic="${key}:general">Evaluación general · ${Object.values(s.topics).reduce((n,t)=>n+t.questions.length,0)} preguntas</button></div><div class="topic-grid">${Object.entries(s.topics).map(([id,t])=>`<article class="topic-card"><div><strong>${escapeHTML(t.name)}</strong><small>${t.questions.length} preguntas</small><button class="text-button" data-diagnostic="${key}:${id}" style="margin-top:8px">Evaluar macrotema →</button></div><span class="mastery-score">${masteryLabel(state.mastery?.[key]?.[id]??null)}</span></article>`).join("")}</div></section>`).join("")}`;bindDiagnosticButtons()}

let diagnostic={subject:null,questions:[],index:0,answers:[]};
function bindDiagnosticButtons(){document.querySelectorAll("[data-diagnostic]").forEach(button=>button.onclick=()=>{const[subject,topic]=button.dataset.diagnostic.split(":");diagnostic={subject,questions:shuffle(diagnosticQuestions(subject,topic==="general"?null:topic)),index:0,answers:[]};drawDiagnostic();document.querySelector("#study-dialog").showModal()})}
function drawDiagnostic(){
  const q=diagnostic.questions[diagnostic.index];document.querySelector("#study-content").innerHTML=`<p class="eyebrow">DIAGNÓSTICO · ${curriculum[diagnostic.subject].name.toUpperCase()}</p><small>Pregunta ${diagnostic.index+1} de ${diagnostic.questions.length}</small><div class="study-question">${escapeHTML(q.text)}</div><div class="diagnostic-options">${q.options.map((o,i)=>`<button class="diagnostic-option" data-choice="${i}">${escapeHTML(o)}</button>`).join("")}</div><button class="primary full" id="diagnostic-next" disabled>${diagnostic.index===diagnostic.questions.length-1?"Finalizar":"Siguiente"}</button>`;
  let choice=null;document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{choice=Number(b.dataset.choice);document.querySelectorAll("[data-choice]").forEach(x=>x.classList.toggle("selected",x===b));document.querySelector("#diagnostic-next").disabled=false});document.querySelector("#diagnostic-next").onclick=()=>{diagnostic.answers.push(choice);diagnostic.index++;diagnostic.index<diagnostic.questions.length?drawDiagnostic():finishDiagnostic()};
}
function finishDiagnostic(){
  const results={};diagnostic.questions.forEach((q,i)=>{const r=results[q.topic]||=( {correct:0,total:0} );r.total++;if(diagnostic.answers[i]===q.correct)r.correct++});state.mastery[diagnostic.subject]||={};Object.entries(results).forEach(([topic,r])=>state.mastery[diagnostic.subject][topic]=Math.round(r.correct/r.total*100));save();if(currentUser)saveDiagnosticResults(diagnostic.subject,results).catch(()=>{});const correct=Object.values(results).reduce((n,r)=>n+r.correct,0),score=Math.round(correct/diagnostic.questions.length*100);
  document.querySelector("#study-content").innerHTML=`<div class="diagnostic-result"><p class="eyebrow">LÍNEA BASE REGISTRADA</p><strong>${score}%</strong><h2>${curriculum[diagnostic.subject].name}</h2><p>Este resultado reorganiza tu prioridad; no define tu capacidad.</p><div class="topic-grid" style="text-align:left">${Object.entries(results).map(([id,r])=>`<div class="topic-card"><div><strong>${curriculum[diagnostic.subject].topics[id].name}</strong><small>${r.correct} de ${r.total}</small></div><span class="mastery-score">${Math.round(r.correct/r.total*100)}%</span></div>`).join("")}</div><button class="primary full" id="diagnostic-close">Ver ruta</button></div>`;document.querySelector("#diagnostic-close").onclick=()=>{document.querySelector("#study-dialog").close();location.hash=diagnostic.subject};awardXP(Math.max(15,correct*4),"diagnóstico completado");
}
function renderQuests(){const quests=[{id:"recall",icon:"◉",title:"Recuperador",text:"Completa 3 tarjetas activas",done:state.reviews>=3,xp:30},{id:"focus",icon:"◷",title:"Enfoque profundo",text:"Termina un bloque de 25 minutos",done:state.focusMinutes>=25,xp:40},{id:"planner",icon:"□",title:"Estratega",text:"Registra un examen con plan",done:Object.keys(state.plans||{}).length>0,xp:25}];app.innerHTML=`<section class="hero"><div><p class="eyebrow">PROGRESIÓN CON PROPÓSITO</p><h1>Misiones</h1><p>Las recompensas reconocen acciones de aprendizaje, no tiempo pasivo.</p></div></section><div class="quest-grid">${quests.map(q=>`<article class="card quest"><div class="quest-icon">${q.icon}</div><h3>${q.title}</h3><p>${q.text}</p><div class="quest-reward"><span>+${q.xp} XP</span><button class="${q.done&&!state.questClaims.includes(q.id)?"primary":"secondary"}" data-claim="${q.id}" ${!q.done||state.questClaims.includes(q.id)?"disabled":""}>${state.questClaims.includes(q.id)?"Reclamada":q.done?"Reclamar":"En curso"}</button></div></article>`).join("")}</div>`;document.querySelectorAll("[data-claim]").forEach(b=>b.onclick=()=>{const q=quests.find(x=>x.id===b.dataset.claim);state.questClaims.push(q.id);awardXP(q.xp,q.title);renderQuests()})}
function renderGroup(){
  const posts=[...(state.communityPosts||[]),{id:"demo",author:"Ana",subject:"Cálculo",title:"¿Cómo detectan qué regla usar?",body:"Estoy intentando explicar primero la estructura de la función antes de derivar. ¿Qué pistas usan ustedes?",helpful:4}];
  app.innerHTML=`<section class="hero"><div><p class="eyebrow">GRUPO PRIVADO</p><h1>Comunidad de estudio</h1><p>Salas con temporizador, preguntas explicadas y retos cooperativos. Con Supabase, el acceso se restringe a invitados.</p></div><div class="date-chip">Código BIO-7K2</div></section><div class="social-layout"><article class="card"><div class="card-title"><h2>Preguntas y explicaciones</h2><span class="due">Solo el grupo</span></div><form class="composer" id="post-form"><input id="post-title" maxlength="120" required placeholder="Pregunta concreta"><textarea id="post-body" maxlength="600" required placeholder="Explica qué entiendes y dónde está la dificultad"></textarea><button class="primary">Compartir</button></form>${posts.map(p=>`<div class="feed-post"><div class="feed-meta"><span class="member-avatar">${initials(p.author)}</span><strong>${escapeHTML(p.author)}</strong><span>· ${escapeHTML(p.subject)}</span></div><h3>${escapeHTML(p.title)}</h3><p>${escapeHTML(p.body)}</p><button class="helpful">△ ${p.helpful||0} · útil</button></div>`).join("")}</article><aside><section class="study-room-live"><p class="eyebrow" style="color:var(--lime)">SALA SILENCIOSA</p><h3>Bloque compartido</h3><div class="room-timer" id="room-timer">25:00</div><div class="room-people"><span class="member-avatar online">AN</span><span class="member-avatar online">${initials(displayName())}</span></div><button class="primary full" id="room-toggle" style="background:var(--lime);color:var(--forest)">Entrar y comenzar</button></section><article class="card" style="margin-top:15px"><h2>Reto semanal</h2><p>Acumulen 300 minutos de recuperación activa.</p><div class="mastery-bar"><i style="width:64%"></i></div><small>192 / 300 minutos</small><a class="primary full" href="#arena" style="text-decoration:none">Entrar a la arena ⚔</a></article></aside></div>`;
  document.querySelector("#post-form").onsubmit=e=>{e.preventDefault();state.communityPosts.unshift({id:uid(),author:displayName(),subject:"General",title:document.querySelector("#post-title").value.trim(),body:document.querySelector("#post-body").value.trim(),helpful:0});save();renderGroup();toast("Aporte compartido")};bindRoomTimer();
}
let arenaDeck=shuffle(allQuestions());let duel={round:0,playerHp:100,enemyHp:100,log:"La precisión importa; la velocidad no da ventaja.",finished:false};
function renderArena(){app.innerHTML=`<section class="hero"><div><p class="eyebrow">DUELOS DE RECUPERACIÓN</p><h1>Arena científica</h1><p>El mazo contiene ${allQuestions().length} preguntas de cuatro cursos y se baraja en cada enfrentamiento.</p></div><div class="date-chip">${state.battleWins||0} victorias</div></section><div id="battle-zone"></div>`;drawDuel()}
function drawDuel(){const zone=document.querySelector("#battle-zone");if(duel.finished){const won=duel.enemyHp<=0;zone.innerHTML=`<article class="card battle-result"><div class="trophy">${won?"🏆":"🧭"}</div><p class="eyebrow">${won?"VICTORIA":"REAGRUPAR"}</p><h2>${won?"Expedición completada":"El guardián resistió"}</h2><p>${won?"Ganaste 50 XP por sostener precisión entre disciplinas.":"No pierdes experiencia: revisa la retroalimentación."}</p><button class="primary" id="duel-restart">Nuevo enfrentamiento</button></article>`;document.querySelector("#duel-restart").onclick=()=>{arenaDeck=shuffle(allQuestions());duel={round:0,playerHp:100,enemyHp:100,log:"Nuevo mazo barajado.",finished:false};drawDuel()};return}const q=arenaDeck[duel.round];zone.innerHTML=`<div class="battle-stage"><div class="fighter"><div class="character"><div class="character-body"></div></div><strong>${escapeHTML(displayName())} · ${levelInfo().name}</strong><small>${duel.playerHp} enfoque</small><div class="hp"><i style="width:${duel.playerHp}%"></i></div></div><div class="vs">VS</div><div class="fighter"><div class="character enemy"><div class="character-body"></div></div><strong>Guardián Entropía</strong><small>${duel.enemyHp} enfoque</small><div class="hp"><i style="width:${duel.enemyHp}%"></i></div></div></div><article class="card battle-question"><p class="eyebrow">RONDA ${duel.round+1} · ${q.subjectName.toUpperCase()}</p><h3>${escapeHTML(q.text)}</h3><div class="battle-options">${q.options.map((o,i)=>`<button class="battle-option" data-answer="${i}">${escapeHTML(o)}</button>`).join("")}</div><div class="battle-log">${escapeHTML(duel.log)}</div></article>`;document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>answerDuel(Number(b.dataset.answer),q))}
function answerDuel(choice,q){if(choice===q.correct){duel.enemyHp=Math.max(0,duel.enemyHp-34);duel.log=`✓ ${q.explanation}`}else{duel.playerHp=Math.max(0,duel.playerHp-25);duel.log=`Correcta: “${q.options[q.correct]}”. ${q.explanation}`}duel.round++;if(duel.enemyHp<=0||duel.playerHp<=0||duel.round>=Math.min(6,arenaDeck.length)){duel.finished=true;if(duel.enemyHp<=0){state.battleWins++;awardXP(50,"victoria científica")}save()}drawDuel()}
function renderMethod(){app.innerHTML=`<section class="hero"><div><p class="eyebrow">EVIDENCIA, NO INTUICIÓN</p><h1>Tu sistema de aprendizaje</h1><p>Equilibra comprensión, memoria duradera y transferencia. La gamificación apoya la constancia, pero no sustituye producir respuestas.</p></div></section><div class="method-grid"><article class="card method-card"><h3>1. Diagnosticar</h3><p>Una prueba breve identifica conocimientos previos y prioridades.</p><h3>2. Comprender y modelar</h3><p>Explicaciones causales y ejemplos trabajados hacen visibles las decisiones.</p><h3>3. Recuperar con retroalimentación</h3><p>Responder sin mirar fortalece el acceso posterior.</p><h3>4. Aplicar e intercalar</h3><p>Alternar problemas enseña a seleccionar principios y transferirlos.</p><h3>5. Espaciar y reevaluar</h3><p>La agenda distribuye intentos antes del examen.</p></article><article class="card"><p class="eyebrow">REFERENCIAS CLAVE</p><ol class="sources"><li>Roediger, H. L., & Karpicke, J. D. (2006). Test-enhanced learning. <em>Psychological Science, 17</em>(3), 249–255. <a href="https://doi.org/10.1111/j.1467-9280.2006.01693.x" target="_blank">doi</a></li><li>Cepeda, N. J., et al. (2006). Distributed practice in verbal recall tasks. <em>Psychological Bulletin, 132</em>(3), 354–380. <a href="https://doi.org/10.1037/0033-2909.132.3.354" target="_blank">doi</a></li><li>Rohrer, D., & Taylor, K. (2007). The shuffling of mathematics problems improves learning. <em>Instructional Science, 35</em>, 481–498. <a href="https://doi.org/10.1007/s11251-007-9015-8" target="_blank">doi</a></li><li>Huang, R., et al. (2020). The impact of gamification in educational settings. <em>ETR&D, 68</em>, 1875–1901. <a href="https://doi.org/10.1007/s11423-020-09807-z" target="_blank">doi</a></li></ol></article></div>`}

let session=[],cardIndex=0,answerShown=false;
function startStudy(key){const pool=key==="mixed"?allQuestions():allQuestions().filter(q=>q.subject===key);session=shuffle(pool).slice(0,Math.min(8,pool.length));cardIndex=0;answerShown=false;drawCard();document.querySelector("#study-dialog").showModal()}
function drawCard(){const c=session[cardIndex];document.querySelector("#study-content").innerHTML=`<p class="eyebrow">RECUPERACIÓN ACTIVA · ${escapeHTML(c.subjectName)}</p><small>Tarjeta ${cardIndex+1} de ${session.length} · ${escapeHTML(c.topicName)}</small><div class="study-question">${escapeHTML(c.text)}</div>${answerShown?`<div class="answer-box"><strong>${escapeHTML(c.options[c.correct])}</strong><br>${escapeHTML(c.explanation)}</div><p>¿Cuánto esfuerzo requirió recuperarla?</p><div class="rating-row"><button class="rating">Difícil · 1 día</button><button class="rating">Bien · 3 días</button><button class="rating">Fácil · 7 días</button></div>`:'<p>Produce una respuesta antes de revelar.</p><button class="primary full" id="reveal">Mostrar respuesta</button>'}`;if(answerShown)document.querySelectorAll(".rating").forEach(b=>b.onclick=rateCard);else document.querySelector("#reveal").onclick=()=>{answerShown=true;drawCard()}}
function rateCard(){state.reviews++;state.xp+=10;state.coins+=2;registerStudyDay();save();cardIndex++;answerShown=false;if(cardIndex>=session.length){document.querySelector("#study-content").innerHTML=`<p class="eyebrow">SESIÓN COMPLETADA</p><h2>Recuperaste ${session.length} ideas</h2><p>Obtuviste ${session.length*10} XP por producir respuestas.</p><button class="primary full" id="finish-study">Terminar</button>`;document.querySelector("#finish-study").onclick=()=>document.querySelector("#study-dialog").close();toast(`+${session.length*10} XP`)}else drawCard()}
function openEventDialog(){updateTopicSelect();const input=document.querySelector("#event-date");if(!input.value){const d=new Date(Date.now()+7*864e5);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());input.value=d.toISOString().slice(0,16)}document.querySelector("#event-dialog").showModal()}
function updateTopicSelect(){const course=document.querySelector("#event-course").value,supported=Boolean(curriculum[course]);document.querySelector("#other-course-wrap").hidden=supported;document.querySelector("#topic-wrap").hidden=!supported;document.querySelector("#event-topic").innerHTML=supported?Object.entries(curriculum[course].topics).map(([id,t])=>`<option value="${id}">${escapeHTML(t.name)}</option>`).join(""):""}
function submitEvent(event){event.preventDefault();const course=document.querySelector("#event-course").value,item={id:uid(),type:document.querySelector("#event-type").value,title:document.querySelector("#event-title").value.trim(),course,courseName:course==="other"?document.querySelector("#event-other-course").value.trim()||"Otro curso":subjects[course].name,topic:course==="other"?null:document.querySelector("#event-topic").value,dueAt:new Date(document.querySelector("#event-date").value).toISOString(),hours:Number(document.querySelector("#event-hours").value),notes:document.querySelector("#event-notes").value.trim()};state.events.push(item);if(item.type==="exam"&&supportedEvent(item))generateExamPlan(item);save();document.querySelector("#event-dialog").close();document.querySelector("#event-form").reset();route();toast(item.type==="exam"&&supportedEvent(item)?"Examen guardado y plan generado":"Actividad guardada")}
function bindCommon(){document.querySelectorAll("[data-study]").forEach(b=>b.onclick=()=>startStudy(b.dataset.study));document.querySelectorAll("[data-new-event]").forEach(b=>b.onclick=openEventDialog);document.querySelectorAll("[data-complete]").forEach(b=>b.onclick=()=>{const id=b.dataset.complete;state.completed=state.completed.includes(id)?state.completed.filter(x=>x!==id):[...state.completed,id];save();route()});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{const id=b.dataset.delete;if(!confirm("¿Eliminar esta actividad?"))return;state.events=state.events.filter(e=>e.id!==id);delete state.plans[id];save();route()});document.querySelectorAll("[data-regenerate]").forEach(b=>b.onclick=()=>{const event=state.events.find(e=>e.id===b.dataset.regenerate);delete state.plans[event.id];generateExamPlan(event);save();renderPlan();toast("Plan recalculado")})}
function bindTimer(){const display=document.querySelector("#timer-display"),toggle=document.querySelector("#timer-toggle"),paint=()=>display.textContent=`${String(Math.floor(timer.remaining/60)).padStart(2,"0")}:${String(timer.remaining%60).padStart(2,"0")}`;paint();toggle.onclick=()=>{if(timer.id){clearInterval(timer.id);timer.id=null;toggle.textContent="Continuar"}else{toggle.textContent="Pausar";timer.id=setInterval(()=>{timer.remaining--;paint();if(timer.remaining<=0){clearInterval(timer.id);timer.id=null;state.focusMinutes+=25;timer.remaining=25*60;awardXP(35,"bloque de enfoque");renderAgenda()}},1000)}};document.querySelector("#timer-reset").onclick=()=>{clearInterval(timer.id);timer.id=null;timer.remaining=25*60;paint();toggle.textContent="Iniciar enfoque"}}
function bindRoomTimer(){const display=document.querySelector("#room-timer"),toggle=document.querySelector("#room-toggle"),paint=()=>display.textContent=`${String(Math.floor(roomTimer.remaining/60)).padStart(2,"0")}:${String(roomTimer.remaining%60).padStart(2,"0")}`;paint();toggle.onclick=()=>{if(roomTimer.id){clearInterval(roomTimer.id);roomTimer.id=null;toggle.textContent="Continuar"}else{toggle.textContent="Pausar";roomTimer.id=setInterval(()=>{roomTimer.remaining--;paint();if(roomTimer.remaining<=0){clearInterval(roomTimer.id);roomTimer.id=null;roomTimer.remaining=25*60;state.focusMinutes+=25;awardXP(35,"sala compartida");renderGroup()}},1000)}}}
function updateChrome(){const info=levelInfo();document.querySelector("#level-orb").textContent=info.level;document.querySelector("#level-name").textContent=info.name;document.querySelector("#xp-label").textContent=`${state.xp} XP`;document.querySelector("#xp-bar").style.width=`${info.progress}%`;document.querySelector("#streak-days").textContent=state.streak||0;document.querySelector("#agenda-count").textContent=sortedEvents().filter(e=>!state.completed.includes(e.id)).length;const available=(state.reviews>=3&&!state.questClaims.includes("recall")?1:0)+(state.focusMinutes>=25&&!state.questClaims.includes("focus")?1:0)+(Object.keys(state.plans).length&&!state.questClaims.includes("planner")?1:0);document.querySelector("#quest-count").textContent=available||Math.max(0,3-state.questClaims.length);const name=displayName();document.querySelector("#profile-name").textContent=name;document.querySelector("#profile-avatar").textContent=initials(name);document.querySelector("#profile-mode").textContent=currentUser?"Sincronización privada":"Modo local";document.querySelector("#account-status").classList.toggle("online",Boolean(currentUser));document.querySelector("#account-login").hidden=Boolean(currentUser);document.querySelector("#account-logout").hidden=!currentUser;document.querySelector("#account-copy").textContent=currentUser?`Sesión activa como ${currentUser.email}. Tu progreso se sincroniza con una fila privada protegida por RLS.`:"En modo local, los datos viven en este navegador. Configura Supabase para sincronizarlos de forma privada entre dispositivos."}
function initWeek(){const names=["L","M","X","J","V","S","D"],day=(new Date().getDay()+6)%7;document.querySelector("#week-dots").innerHTML=names.map((n,i)=>`<span class="day-dot ${i<day&&state.streak?"done":i===day?"today":""}"><i></i>${n}</span>`).join("")}
function toast(message){const t=document.querySelector("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3000)}
async function initializeAccount(){const gate=document.querySelector("#access-gate");if(!isSocialConfigured()){gate.hidden=true;updateChrome();return}currentUser=await getCurrentUser();gate.hidden=Boolean(!(NUCLEO_CONFIG.requireAccount&&!currentUser));if(currentUser){try{const cloud=await loadLearningState();if(cloud)state={...structuredClone(initial),...cloud};else await saveLearningState(state);localStorage.setItem("nucleo-state",JSON.stringify(state))}catch{toast("No se pudo leer la nube; se conserva la copia local")}}updateChrome();route();await onAuthChange(user=>{currentUser=user;gate.hidden=Boolean(!(NUCLEO_CONFIG.requireAccount&&!user));updateChrome()})}

document.documentElement.dataset.theme=localStorage.getItem("nucleo-theme")||"light";
document.querySelector("#theme-toggle").onclick=()=>{const next=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=next;localStorage.setItem("nucleo-theme",next)};
document.querySelector("#menu-button").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");
document.querySelector("#quick-focus").onclick=()=>{location.hash="agenda";setTimeout(()=>document.querySelector("#timer-toggle")?.click(),150)};
document.querySelector("#new-event-button").onclick=openEventDialog;document.querySelector("#event-course").onchange=updateTopicSelect;document.querySelector("#event-form").onsubmit=submitEvent;
document.querySelectorAll("#account-button,#profile-button").forEach(b=>b.onclick=()=>document.querySelector("#account-dialog").showModal());document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.querySelector(`#${b.dataset.close}`).close());
document.querySelectorAll("#gate-google-button,#account-login").forEach(b=>b.onclick=()=>signInWithGoogle().catch(e=>toast(e.message)));
document.querySelector("#account-logout").onclick=async()=>{await signOut();currentUser=null;document.querySelector("#account-dialog").close();if(NUCLEO_CONFIG.requireAccount)document.querySelector("#access-gate").hidden=false;updateChrome()};
document.querySelector("#reset-demo").onclick=()=>{if(!confirm("¿Reiniciar el progreso, la agenda y los planes?"))return;state=structuredClone(initial);save();document.querySelector("#account-dialog").close();route();toast("Datos reiniciados")};
window.addEventListener("hashchange",route);initWeek();updateChrome();route();initializeAccount();
